### ISSUE TITLE
TypeError: a bytes-like object is required, not 'str'

### ISSUE THREAD

**Issue by cmdaltr** [davidpany/WMI_Forensics#8]
I run the following command and receive the following error:

```
python3 CCM_RUA_Finder.py -i OBJECTS.DATA -o OBJECTS.DATA.xls
                0.0% complete...Traceback (most recent call last):
  File "/Users/Ben/Desktop/elrond_dev/WMI_Forensics/CCM_RUA_Finder.py", line 554, in <module>
    main()
  File "/Users/Ben/Desktop/elrond_dev/WMI_Forensics/CCM_RUA_Finder.py", line 241, in main
    all_ccm_data_set = find_ccm_rua_data(args.input)
  File "/Users/Ben/Desktop/elrond_dev/WMI_Forensics/CCM_RUA_Finder.py", line 191, in find_ccm_rua_data
    if "CCM_RecentlyUsedApps" in current_buffer:
TypeError: a bytes-like object is required, not 'str'
```

**Comment by hkphh** [comment]
@ezaspy same error. I've run it with python2.7 and it works. Guys use full path to your script and python.exe!
command(run with py2.7):
C:\Python27\python.exe С:\Python27\CCM_RUA_Finder.py -i C:\WINDOWS\system32\wbem\Repository\OBJECTS.DATA -o output.xls

**Comment by cmdaltr** [comment]
Thank you - will close
